#!/bin/sh

# verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkd="mkdir -pv"
alias rsync="rsync -vrPlu"
alias yt="yt-dlp --embed-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ytt="yt --skip-download --write-thumbnail"
alias ffmpeg="ffmpeg -hide_banner"

# colorize commands when possible.
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"
alias ip="ip -color=auto"
alias cat="batcat"

# -------------------- navigation --------------------
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# -------------------- shortcut aliases --------------------
# apt
alias install="sudo apt install"
alias remove="sudo apt remove"
alias update="sudo apt update"
alias upgrade="sudo apt upgrade"
alias autoremove="sudo apt autoremove"
# apt source list
alias lt-src="lt /etc/apt/ --level=3"
# adding flags
alias df='df -h'
alias free='free -m'
# ps
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"
alias psmem='ps auxf | sort -nr -k 4'
alias pscpu='ps auxf | sort -nr -k 3'
alias chs="tldr --list | fzf --preview 'tldr {1}' | xargs tldr"
alias cfg='fdfind -t f -H . ~/dotfiles | fzf --preview="batcat --color=always {} | head -200" | xargs -or vim'

# -------------------- eza (better ls) --------------------
alias ls="eza --icons -a"
alias lsg="ls --group-directories-first"
alias lt="eza --icons -lha --git --tree --level=2 --ignore-glob='.git|node_modules|.next'"
alias ltg="lt --group-directories-first"
alias l="eza --icons -lgha --git"
alias lg="l --group-directories-first"
alias l.='lsg -1 ../' # ls on the PARENT directory
alias l..='lsg -1 ../../' # ls on directory 2 levels up
alias l...='lsg -1 ../../../' # ls on directory 3 levels up

# -------------------- vim --------------------
alias v="vi"
alias n="nvim"
# neovim switcher
ns() {
  # Assumes all configs exist in directories named ~/.config/nvim-*
  local config=$(find -L ~/.config -maxdepth 1 -name 'nvim-*' | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  # If I exit fzf without selecting a config, don't open Neovim
  [[ -z $config ]] && echo "No config selected" && return
  # Open Neovim with the selected config
  NVIM_APPNAME=$(basename $config) nvim $@
}

# -------------------- git --------------------
alias g="git"
alias gc="git commit -m"
alias gca="git commit -a -m"
alias gp="git push origin HEAD"
alias gpu="git pull origin"
alias gst="git status"
alias gdiff="git diff"
alias gco="git checkout"
alias gb='git branch'
alias gba='git branch -a'
alias ga='git add -p'
alias gcoall='git checkout -- .'
alias glog="git log --graph --topo-order --pretty='%w(100,0,6)%C(yellow)%h%C(bold)%C(black)%d %C(cyan)%ar %C(green)%an%n%C(bold)%C(white)%s %N' --abbrev-commit"
alias gcb='git branch --sort=-committerdate | fzf --header "Checkout Recent Branch" --preview "git diff --color=always {1}" --pointer="" | xargs git checkout'

bins() {
  choice="$(find -L ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
  [ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

### ARCHIVE EXTRACTION
# usage: ex <file>
function ex {
  if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: ex <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
    echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
  else
    for n in "$@"
    do
      if [ -f "$n" ] ; then
        case "${n%,}" in
          *.cbt|*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar)
                              tar xvf "$n"         ;;
          *.lzma)             unlzma ./"$n"        ;;
          *.bz2)              bunzip2 ./"$n"       ;;
          *.cbr|*.rar)        unrar x -ad ./"$n"   ;;
          *.gz)               gunzip ./"$n"        ;;
          *.cbz|*.epub|*.zip) unzip ./"$n"         ;;
          *.z)                uncompress ./"$n"    ;;
          *.7z|*.arj|*.cab|*.cb7|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.pkg|*.rpm|*.udf|*.wim|*.xar)
                              7z x ./"$n"          ;;
          *.xz)               unxz ./"$n"          ;;
          *.exe)              cabextract ./"$n"    ;;
          *.cpio)             cpio -id < ./"$n"    ;;
          *.cba|*.ace)        unace x ./"$n"       ;;
          *)                  echo "ex: '$n' - unknown archive method"
                              return 1             ;;
        esac
      else
        echo "'$n' - file does not exist"
        return 1
      fi
    done
  fi
}

