#!/bin/sh

typeset -U PATH path
# unsetopt PROMPT_SP 2>/dev/null

# add all directories in `~/.local/bin/` to $PATH
export PATH="$PATH:$(find -L ~/.local/bin -type d | paste -sd ':' -)"
# neovim
export PATH="$XDG_LIB_HOME/nvim-linux-x86_64/bin:$PATH"
# bun
export PATH="$BUN_INSTALL/bin:$PATH"
# dotnet
export PATH="${DOTNET_ROOT:-$XDG_LIB_HOME/dotnet}:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"
# go
export PATH="/usr/local/go/bin:${GOROOT:-$XDG_LIB_HOME/go}/bin:${GOPATH:-$XDG_DATA_HOME/go}/bin:$PATH"
# php
export PATH="$XDG_CONFIG_HOME/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="$XDG_CONFIG_HOME/herd-lite/bin:$PHP_INI_SCAN_DIR"

# -------------------- default programs --------------------
export BROWSER="google-chrome"
export EDITOR="vim"
export SUDO_EDITOR="vim"
export TERMINAL="kitty"
export READER="zathura"
export VIDEO="mpv"
export IMAGE="sxiv"
export COLORTERM="truecolor"
export OPENER="xdg-open"
# export PAGER="moar"

