#!/bin/sh

typeset -U PATH path
# unsetopt PROMPT_SP 2>/dev/null

# add all directories in `~/.local/bin/` to $PATH
export PATH="$PATH:$(find -L ~/.local/bin -type d | paste -sd ':' -)"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="${DOTNET_ROOT:-$HOME/.local/share/dotnet}:$HOME/.dotnet/tools:$PATH"
export PATH="/usr/local/go/bin:$HOME/.local/lib/go/bin:${GOPATH:-$HOME/.local/share/go}/bin:$PATH"
export PATH="$HOME/.config/herd-lite/bin:$PATH"
export PATH="$HOME/.local/lib/nvim-linux-x86_64/bin:$PATH"
export PHP_INI_SCAN_DIR="$HOME/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"

# -------------------- default programs --------------------
export BROWSER="google-chrome"
export EDITOR="vim"
export SUDO_EDITOR="vim"
export TERMINAL="kitty"
export READER="zathura"
export VIDEO="mpv"
export IMAGE="sxiv"
export COLORTERM="truecolor"
export OPENER="xdg-open"
# export PAGER="moar"

